version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./EventMaster.Web/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db

  client:
    build:
      context: ./eventmaster.client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web

  db:
    build:
      context: ./EventMaster.Database
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
