services:
  # 1. Контейнер с бэкендом (EventMaster.Web)
  web:
    build:
      context: .
      dockerfile: ./EventMaster.Web/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__EventMasterDb=Server=db;Database=EventMasterDb;User=sa;Password=YourStrong!Passw0rd
    depends_on:
      - db

  # 2. Контейнер с React (eventmaster.client)
  client:
    build:
      context: ./eventmaster.client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      # Значение, которое попадёт в config.json через envsubst
      - SERVER_HOST_ADDRESS=http://web:80
    depends_on:
      - web

  # 3. Контейнер с SQL Server (кастомный образ с инициализацией)
  db:
    build:
      context: ./EventMaster.Database
      dockerfile: Dockerfile
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
