version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./EventMaster.Web/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__EventMasterDb=Server=db;Database=EventMasterDb;User=sa;Password=YourStrong!Passw0rd
    depends_on:
      - db

  client:
    build:
      context: ./eventmaster.client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./EventMaster.Database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  mssql_data: