services:
  web:
    build:
      context: ./
      dockerfile: ./EventMaster.Web/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./eventmaster.client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web

  db:
    ports:
      - "1433:1433"
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
        - ./EventMaster.Database/init-db.sql:/docker-entrypoint-initdb.d/init-script.sql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
